name: Update Scoreboard
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: 23seriy/readme-scoreboard@main
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          api_key: ${{ secrets.BDL_API_KEY }}
          sport: nba
          team: LAL

      - uses: 23seriy/readme-scoreboard@main
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          sport: mlb
          team: TOR
          marker: readme-scoreboard-mlb

      - uses: 23seriy/readme-scoreboard@main
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          sport: nhl
          team: TOR
          marker: readme-scoreboard-nhl

      - uses: 23seriy/readme-scoreboard@main
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          sport: nfl
          team: NE
          marker: readme-scoreboard-nfl

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet README.md || (git add README.md && git commit -m "🏀⚾🏒🏈 Update NBA + MLB + NHL + NFL scoreboard" && git push)
